theme: jekyll-theme-minimal
logo: https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Tool_box_icon-01.svg/165px-Tool_box_icon-01.svg.png
show_downloads: "true"
google_analytics: [Your Google Analytics tracking ID]
